// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package uart2_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {logic q;} tx_watermark;
    struct packed {logic q;} rx_watermark;
    struct packed {logic q;} tx_empty;
    struct packed {logic q;} rx_overflow;
    struct packed {logic q;} rx_frame_err;
    struct packed {logic q;} rx_break_err;
    struct packed {logic q;} rx_timeout;
    struct packed {logic q;} rx_parity_err;
  } uart2_reg2hw_intr_state_reg_t;

  typedef struct packed {
    struct packed {logic q;} tx_watermark;
    struct packed {logic q;} rx_watermark;
    struct packed {logic q;} tx_empty;
    struct packed {logic q;} rx_overflow;
    struct packed {logic q;} rx_frame_err;
    struct packed {logic q;} rx_break_err;
    struct packed {logic q;} rx_timeout;
    struct packed {logic q;} rx_parity_err;
  } uart2_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic q;
      logic qe;
    } tx_watermark;
    struct packed {
      logic q;
      logic qe;
    } rx_watermark;
    struct packed {
      logic q;
      logic qe;
    } tx_empty;
    struct packed {
      logic q;
      logic qe;
    } rx_overflow;
    struct packed {
      logic q;
      logic qe;
    } rx_frame_err;
    struct packed {
      logic q;
      logic qe;
    } rx_break_err;
    struct packed {
      logic q;
      logic qe;
    } rx_timeout;
    struct packed {
      logic q;
      logic qe;
    } rx_parity_err;
  } uart2_reg2hw_intr_test_reg_t;

  typedef struct packed {
    struct packed {logic q;} tx;
    struct packed {logic q;} rx;
    struct packed {logic q;} nf;
    struct packed {logic q;} slpbk;
    struct packed {logic q;} llpbk;
    struct packed {logic q;} parity_en;
    struct packed {logic q;} parity_odd;
    struct packed {logic [1:0] q;} rxblvl;
    struct packed {logic [15:0] q;} nco;
  } uart2_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic q;
      logic re;
    } txfull;
    struct packed {
      logic q;
      logic re;
    } rxfull;
    struct packed {
      logic q;
      logic re;
    } txempty;
    struct packed {
      logic q;
      logic re;
    } txidle;
    struct packed {
      logic q;
      logic re;
    } rxidle;
    struct packed {
      logic q;
      logic re;
    } rxempty;
  } uart2_reg2hw_status_reg_t;

  typedef struct packed {
    logic [7:0] q;
    logic       re;
  } uart2_reg2hw_rdata_reg_t;

  typedef struct packed {
    logic [7:0] q;
    logic       qe;
  } uart2_reg2hw_wdata_reg_t;

  typedef struct packed {
    struct packed {
      logic q;
      logic qe;
    } rxrst;
    struct packed {
      logic q;
      logic qe;
    } txrst;
    struct packed {
      logic [2:0] q;
      logic       qe;
    } rxilvl;
    struct packed {
      logic [1:0] q;
      logic       qe;
    } txilvl;
  } uart2_reg2hw_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {logic q;} txen;
    struct packed {logic q;} txval;
  } uart2_reg2hw_ovrd_reg_t;

  typedef struct packed {
    struct packed {logic [23:0] q;} val;
    struct packed {logic q;} en;
  } uart2_reg2hw_timeout_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } tx_watermark;
    struct packed {
      logic d;
      logic de;
    } rx_watermark;
    struct packed {
      logic d;
      logic de;
    } tx_empty;
    struct packed {
      logic d;
      logic de;
    } rx_overflow;
    struct packed {
      logic d;
      logic de;
    } rx_frame_err;
    struct packed {
      logic d;
      logic de;
    } rx_break_err;
    struct packed {
      logic d;
      logic de;
    } rx_timeout;
    struct packed {
      logic d;
      logic de;
    } rx_parity_err;
  } uart2_hw2reg_intr_state_reg_t;

  typedef struct packed {
    struct packed {logic d;} txfull;
    struct packed {logic d;} rxfull;
    struct packed {logic d;} txempty;
    struct packed {logic d;} txidle;
    struct packed {logic d;} rxidle;
    struct packed {logic d;} rxempty;
  } uart2_hw2reg_status_reg_t;

  typedef struct packed {logic [7:0] d;} uart2_hw2reg_rdata_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0] d;
      logic       de;
    } rxilvl;
    struct packed {
      logic [1:0] d;
      logic       de;
    } txilvl;
  } uart2_hw2reg_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {logic [10:0] d;} txlvl;
    struct packed {logic [10:0] d;} rxlvl;
  } uart2_hw2reg_fifo_status_reg_t;

  typedef struct packed {logic [15:0] d;} uart2_hw2reg_val_reg_t;

  // Register -> HW type
  typedef struct packed {
    uart2_reg2hw_intr_state_reg_t intr_state;  // [124:117]
    uart2_reg2hw_intr_enable_reg_t intr_enable;  // [116:109]
    uart2_reg2hw_intr_test_reg_t intr_test;  // [108:93]
    uart2_reg2hw_ctrl_reg_t ctrl;  // [92:68]
    uart2_reg2hw_status_reg_t status;  // [67:56]
    uart2_reg2hw_rdata_reg_t rdata;  // [55:47]
    uart2_reg2hw_wdata_reg_t wdata;  // [46:38]
    uart2_reg2hw_fifo_ctrl_reg_t fifo_ctrl;  // [37:27]
    uart2_reg2hw_ovrd_reg_t ovrd;  // [26:25]
    uart2_reg2hw_timeout_ctrl_reg_t timeout_ctrl;  // [24:0]
  } uart2_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    uart2_hw2reg_intr_state_reg_t intr_state;  // [64:49]
    uart2_hw2reg_status_reg_t status;  // [48:43]
    uart2_hw2reg_rdata_reg_t rdata;  // [42:35]
    uart2_hw2reg_fifo_ctrl_reg_t fifo_ctrl;  // [34:28]
    uart2_hw2reg_fifo_status_reg_t fifo_status;  // [27:16]
    uart2_hw2reg_val_reg_t val;  // [15:0]
  } uart2_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] UART2_INTR_STATE_OFFSET = 6'h0;
  parameter logic [BlockAw-1:0] UART2_INTR_ENABLE_OFFSET = 6'h4;
  parameter logic [BlockAw-1:0] UART2_INTR_TEST_OFFSET = 6'h8;
  parameter logic [BlockAw-1:0] UART2_CTRL_OFFSET = 6'hc;
  parameter logic [BlockAw-1:0] UART2_STATUS_OFFSET = 6'h10;
  parameter logic [BlockAw-1:0] UART2_RDATA_OFFSET = 6'h14;
  parameter logic [BlockAw-1:0] UART2_WDATA_OFFSET = 6'h18;
  parameter logic [BlockAw-1:0] UART2_FIFO_CTRL_OFFSET = 6'h1c;
  parameter logic [BlockAw-1:0] UART2_FIFO_STATUS_OFFSET = 6'h20;
  parameter logic [BlockAw-1:0] UART2_OVRD_OFFSET = 6'h24;
  parameter logic [BlockAw-1:0] UART2_VAL_OFFSET = 6'h28;
  parameter logic [BlockAw-1:0] UART2_TIMEOUT_CTRL_OFFSET = 6'h2c;

  // Reset values for hwext registers and their fields
  parameter logic [7:0] UART2_INTR_TEST_RESVAL = 8'h0;
  parameter logic [0:0] UART2_INTR_TEST_TX_WATERMARK_RESVAL = 1'h0;
  parameter logic [0:0] UART2_INTR_TEST_RX_WATERMARK_RESVAL = 1'h0;
  parameter logic [0:0] UART2_INTR_TEST_TX_EMPTY_RESVAL = 1'h0;
  parameter logic [0:0] UART2_INTR_TEST_RX_OVERFLOW_RESVAL = 1'h0;
  parameter logic [0:0] UART2_INTR_TEST_RX_FRAME_ERR_RESVAL = 1'h0;
  parameter logic [0:0] UART2_INTR_TEST_RX_BREAK_ERR_RESVAL = 1'h0;
  parameter logic [0:0] UART2_INTR_TEST_RX_TIMEOUT_RESVAL = 1'h0;
  parameter logic [0:0] UART2_INTR_TEST_RX_PARITY_ERR_RESVAL = 1'h0;
  parameter logic [5:0] UART2_STATUS_RESVAL = 6'h3c;
  parameter logic [0:0] UART2_STATUS_TXEMPTY_RESVAL = 1'h1;
  parameter logic [0:0] UART2_STATUS_TXIDLE_RESVAL = 1'h1;
  parameter logic [0:0] UART2_STATUS_RXIDLE_RESVAL = 1'h1;
  parameter logic [0:0] UART2_STATUS_RXEMPTY_RESVAL = 1'h1;
  parameter logic [7:0] UART2_RDATA_RESVAL = 8'h0;
  parameter logic [21:0] UART2_FIFO_STATUS_RESVAL = 22'h0;
  parameter logic [15:0] UART2_VAL_RESVAL = 16'h0;

  // Register index
  typedef enum int {
    UART2_INTR_STATE,
    UART2_INTR_ENABLE,
    UART2_INTR_TEST,
    UART2_CTRL,
    UART2_STATUS,
    UART2_RDATA,
    UART2_WDATA,
    UART2_FIFO_CTRL,
    UART2_FIFO_STATUS,
    UART2_OVRD,
    UART2_VAL,
    UART2_TIMEOUT_CTRL
  } uart2_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] UART2_PERMIT[12] = '{
      4'b0001,  // index[ 0] UART2_INTR_STATE
      4'b0001,  // index[ 1] UART2_INTR_ENABLE
      4'b0001,  // index[ 2] UART2_INTR_TEST
      4'b1111,  // index[ 3] UART2_CTRL
      4'b0001,  // index[ 4] UART2_STATUS
      4'b0001,  // index[ 5] UART2_RDATA
      4'b0001,  // index[ 6] UART2_WDATA
      4'b0001,  // index[ 7] UART2_FIFO_CTRL
      4'b0111,  // index[ 8] UART2_FIFO_STATUS
      4'b0001,  // index[ 9] UART2_OVRD
      4'b0011,  // index[10] UART2_VAL
      4'b1111  // index[11] UART2_TIMEOUT_CTRL
  };

endpackage

